[package]
name = "iron-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1", features = ["v4"] }
nix = { version = "0.27.1", features = ["process"] }
log = "0.4.20"
